# .travis.yml:

        language: php

        php:
        - "7.1"

        branches:

        env:
        matrix:
        global:
        secure: "HL7CjhEYsuZSN3CHaysseY32B9zqiirtlb5QtG5HsR5zD4s32ROdR7BymkZyn/2KxI4+fiMkeKQ5xA1akH8BvgdfE8OcsJmCPsPvEWuRYRHXmbCbwHOsupcg68BJtpUQwb+dNvNmde0uaL4dIG8cAUiXw67SB8gOx3cVgpW2N34="

        before_script:
        - composer self-update
        - composer install --no-interaction

        script:
        - phpunit

        after_script:

        after_success:
        - bash build_success.sh;

        after_failure:
        notifications:
        email:
        recipients:
        - sergey.i.che@gmail.com
        on_success: always
        on_failure: always